name: Publish in Open VSX Registry
run-name: ${{ github.triggering_actor }} is publishing in Open VSX Registry from ${{ github.ref_name }}
on:
  workflow_dispatch: #  Button for publishing from input branch in case there is a failure on the release.

jobs:
  publish-start-notification:
    name: 'Publish Agentforce DX in Open VSX Start Notification'
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
  #    don't publish to ovsx until stable
  #    with:
  #      title: 'Publish Agentforce DX in Open VSX waiting for approval in github.'
  #      notification: 'New Release triggered publish build and job is ready for approval.'
  #      type: 'notification'
  #      workflow: 'publishOpenVSX.yml'
  get-release-version:
    uses: ./.github/workflows/getReleaseVersion.yml
    secrets: inherit
  output-release-version:
    runs-on: ubuntu-latest
    needs: [get-release-version]
    steps:
      - run: echo "Publishing version ${{ needs.get-release-version.outputs.release-version }}"
  publish:
    needs: [get-release-version]
    runs-on: ubuntu-latest
    env:
      OVSX_PAT: ${{ secrets.IDEE_OVSX_PAT }}
      PUBLISH_VERSION: ${{ needs.get-release-version.outputs.release-version }}
      GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: downloadExtensionsFromRelease
        run: |
          mkdir ./extensions
          gh release download v${{ env.PUBLISH_VERSION }} -D ./extensions
      - name: Display downloaded vsix files
        run: ls -R ./extensions
      - name: Configure Git for private repo access
        run: git config --global --add url."https://${{ secrets.IDEE_GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: npm ci
      - run: find ./extensions -type f -name "vscode-agents*.vsix" -exec npx ovsx publish {} -p ${{ env.OVSX_PAT }} \;
      - run: echo "SUCCESSFULLY published"
